bind-key -r h select-pane -L
bind-key -r j select-pane -U
bind-key -r k select-pane -D
bind-key -r l select-pane -R

bind-key -rn M-h resize-pane -L 5
bind-key -rn M-j resize-pane -U 5
bind-key -rn M-k resize-pane -D 5
bind-key -rn M-l resize-pane -R 5

set -g status-interval 3
set -g status-justify absolute-centre
set -g status-style "bg=black fg=white bold"
set -g visual-activity on
set -g window-status-current-style "bg=brightblue fg=black"
