# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" "lvm" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/62d32fa8-7e44-45ee-93ce-214b86635fe9";
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b3e3f378-60a4-46cc-92fb-b3afa3654d17";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/a5d18ab7-ee1c-4af3-9b44-2610d9f8e4b4"; }
    ];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
