alias ls='ls --color'
alias ll='ls -lh --color'
alias l='ls -alh --color'
alias grep='grep --color'
alias cls='clear'
alias x='exit'

alias ya='yaourt'
alias sprunge='curl -F "sprunge=<-" http://spunge.us'
alias yld='curl --data-binary @- https://yld.me/paste <'
