alias ls='ls --color'
alias ll='ls -lh --color'
alias l='ls -alh --color'
alias grep='grep --color'
alias cls='clear'
alias x='exit'

alias g='git'
alias gst='git status'
alias gcl='git clone --recursive'
alias gc='git commit -v'
alias gca='git commit -av'
alias ga='git add'
alias gaa='git add -A'
alias gco='git checkout'
alias gcb='git checkout -b'
alias gb='git branch'
alias gr='git remote'
alias grv='git remote -v'
alias gl='git pull'
alias gp='git push'
alias gd='git diff -v'

alias ya='yaourt'
