alias ls='ls --color'
alias ll='ls -lh --color'
alias l='ls -alh --color'
alias grep='grep --color'
alias cls='clear'
alias x='exit'

alias g='git'
alias gst='git status'
alias gcl='git clone --recursive'
alias gc='git commit'
alias gca='git commit -a'
alias gaa='git add -A'
alias gco='git checkout'
alias gcb='git checkout --branch'
alias gb='git branch'
alias gr='git remote'
alias grv='git remote -v'

alias ya='yaourt'
